### ISSUE TITLE
go_binary produces non-reproducible builds when run in sandbox

### ISSUE THREAD

**Issue by chrismcbride** [bazelbuild/rules_go#198]
The debug symbols included in the output binary contain the full source path, including the sandbox directory. The sandbox directory contains a random string which causes subsequent builds to not be bit identical.

#### Versions
> bazel version
Build label: 0.4.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 2 17:54:14 2016 (1478109254)
Build timestamp: 1478109254
Build timestamp as int: 1478109254

> git_repository(
  name = 'io_bazel_rules_go',
  remote = 'https://github.com/bazelbuild/rules_go.git',
  tag = '0.3.0',
)

#### Steps to reproduce

BUILD
```
load('@io_bazel_rules_go//go:def.bzl', 'go_binary')
go_binary(
  name = 'main',
  srcs = [
    'main.go',
  ],
)
```

main.go
```
package main

func main() {
  panic("")
}
```

```
# bazel build :main
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main.a
  bazel-bin/main
INFO: Elapsed time: 2.715s, Critical Path: 0.28s

# sha256sum ./bazel-bin/main
7c58071a6919403bf24734625cdc52c2470504b5f7d1886a14131dd19c4d57c6  ./bazel-bin/main

# strings ./bazel-bin/main | grep sandbox | head -1
/root/.cache/bazel/_bazel_root/8cd13b75700216788cbc2043831c737d/bazel-sandbox/898a4e66-f734-4887-a12b-4fbd444ccf32-1/execroot/app/external/io_bazel_rules_go_toolchain/src/runtime/internal/atomic/asm_amd64.s

# bazel clean
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.

# bazel build :main
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main.a
  bazel-bin/main
INFO: Elapsed time: 2.559s, Critical Path: 0.27s

# sha256sum ./bazel-bin/main
8b65912454483f16a92b9c1936262570d74bf80756220d359ebb9b7588d5fc96  ./bazel-bin/main

# strings ./bazel-bin/main | grep sandbox | head -1
/root/.cache/bazel/_bazel_root/8cd13b75700216788cbc2043831c737d/bazel-sandbox/40393696-db64-493f-9895-4fcfecaa75e0-1/execroot/app/external/io_bazel_rules_go_toolchain/src/runtime/internal/atomic/asm_amd64.s
```

**Comment by pmbethe09** [comment]
We should fix that.

**Comment by chrismcbride** [comment]
FWIW exporting "GOROOT_FINAL=/" in all of the rule impls does make the debug symbols for stdlib functions consistent. I'm not sure how to handle the GOPATH dependencies yet.

**Comment by chrismcbride** [comment]
```diff
diff --git a/go/def.bzl b/go/def.bzl
index baf535a..f4bedcc 100644
--- a/go/def.bzl
+++ b/go/def.bzl
@@ -129,6 +129,7 @@ def emit_go_asm_action(ctx, source, out_obj):
       ctx.file.go_tool.path, "tool", "asm",
       "-I", ctx.file.go_include.path,
       "-o", out_obj.path,
+      "-trimpath", "$(pwd)",
       source.path,
   ]
   cmds = [
@@ -200,12 +201,14 @@ def emit_go_compile_action(ctx, sources, deps, out_lib, extra_objects=[]):
       ('../' * out_depth) + ctx.file.go_tool.path,
       "tool", "compile",
       "-o", ('../' * out_depth) + out_lib.path, "-pack",
-      "-I", "."
+      "-I", ".",
+      "-trimpath", "$(pwd)",
   ]
 
   # Set -p to the import path of the library, ie.
   # (ctx.label.package + "/" ctx.label.name) for now.
-  cmds += [ "export GOROOT=$(pwd)/" + ctx.file.go_tool.dirname + "/..",
+  cmds += [
+    "export GOROOT=$(pwd)/" + ctx.file.go_tool.dirname + "/..",
     ' '.join(args + cmd_helper.template(set(sources), prefix + "%{path}"))]
   extra_inputs = ctx.files.toolchain
 
@@ -391,6 +394,7 @@ def emit_go_link_action(ctx, importmap, transitive_libs, cgo_deps, lib,
   # or earlier.
   cmds += ["export PATH=$PATH:/usr/bin"]
   cmds += [
+    "export GOROOT_FINAL=/",
     "export GOROOT=$(pwd)/" + ctx.file.go_tool.dirname + "/..",
     "cd " + out_dir,
     ' '.join(link_cmd),
```

This almost works...except for cgo libraries. Since the cgo library .go files are generated in a different action than the go compile command, just stripping $(pwd) doesn't work because the cgo files will have a different sandbox id in their path.

One solution would be to copy all the files with a different path before compiling, not sure if there is a more idiomatic way to solve this.

**Comment by chrismcbride** [comment]
FWIW now that the rules no longer symlink, this works correctly for the provided example. Its only cgo libraries that are still a problem.

**Comment by AustinSchuh** [comment]
This problem is still around.  Has there been any progress?

I tried the patch (-trimpath), but '$(pwd)' isn't being expanded.  I poked around in ctx a bit and couldn't find anything that would give me the sandbox path.

**Comment by jayconrod** [comment]
Just confirmed: still broken even for pure-Go binaries.

When running strings and grepping for my username, I see a lot of paths to source files in the standard library. `readelf -x` tells me these strings are in `.golntab`, which is a table used to create stack traces. I'm told the linker may be adding these.
