### ISSUE TITLE
Failed to detect SDK platform on Windows 10

### ISSUE THREAD

**Issue by c16a** [bazelbuild/rules_go#2345]
### What version of rules_go are you using?
0.21.0

### What version of gazelle are you using?
0.19.1

### What version of Bazel are you using?
Build label: 2.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:31:16 2019 (1576758676)
Build timestamp: 1576758676
Build timestamp as int: 1576758676

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Windows 10, AMD64

### What did you do?
Tried using `go_host_sdk` with the path of my local Go SDK

### What did you expect to see?
`bazel build //...` should correctly build my Go targets

### What did you see instead?
```
ERROR: While resolving toolchains for target //lib/db:go_default_library: invalid registered toolchain '@go_sdk//:go_android_386': no such package '@go_sdk//': Traceback (most recent call last):
        File "C:/users/xxxx/_bazel_xxxx/7rcsayal/external/io_bazel_rules_go/go/private/sdk.bzl", line 41
                _detect_sdk_platform(ctx, <1 more arguments>)
        File "C:/users/xxxx/_bazel_xxxx/7rcsayal/external/io_bazel_rules_go/go/private/sdk.bzl", line 236, in _detect_sdk_platform
                fail(<1 more arguments>)
Could not detect SDK platform
```
Similar errors are thrown for `@go_sdk//:go_android_amd64` etc., all the toolchains that I did not register, or did not use in my source. Bazel only complains about the first invalid toolchain. When run again, the toolchain differs, but the complaint is the same.

**Comment by c16a** [comment]
@jayconrod, I noticed something below

https://github.com/bazelbuild/rules_go/blob/4af399c5cc92a57cb9f88c1822e9bf886934f1d0/go/private/sdk.bzl#L233

The above command tries to perform `ctx.execute(["ls", goroot + "/pkg/tool"])`. 

But when I stat the `GOROOT`, I nicely get `windows_amd64`. So there seems to be no issue with my Go SDK / GOROOT environment. Both `go env GOROOT` and `echo %GOROOT%` point to my Go SDK installation.

Are these issues the remnants of the earlier Windows compatibilities issues that had workarounds by using MSYS2, CYGWIN etc.?

Any thoughts on how to fix?

**Comment by jayconrod** [comment]
I think this code is from before we supported Windows. At the time, there was no way to list a directory on Windows, except by running a command.

It can probably be done with [`path.readdir`](https://docs.bazel.build/versions/master/skylark/lib/path.html#readdir) now.

**Comment by c16a** [comment]
But this still is on HEAD of rules_go, and is pointed to directly by the error log. Is there anything that I'd need to fix in my WORKSPACE?

**Comment by jayconrod** [comment]
It's a bug that should be fixed in the rule implementation.

MSYS2 is necessary. I think bash is still used in a couple places. patch is necessary for repository rules.

**Comment by adam-azarchs** [comment]
I get a similar failure,
```
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
        File "C:/users/azarchs/_bazel_azarchs/4q2alav3/external/io_bazel_rules_go/go/private/sdk.bzl", line 32, column 36, in _go_host_sdk_impl
                platform = _detect_sdk_platform(ctx, goroot)
        File "C:/users/azarchs/_bazel_azarchs/4q2alav3/external/io_bazel_rules_go/go/private/sdk.bzl", line 286, column 13, in _detect_sdk_platform
                fail("Could not detect SDK platform: unable to list %s: %s" % (path, res.stderr))
Error in fail: Could not detect SDK platform: unable to list C:\Program Files\Go/pkg/tool: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("ls" "C:\Program Files\Go/pkg/tool"): The system cannot find the file specified.
 (error: 2)
 ```
I believe in this case the issue is the the whitespace in `Program Files`, because `CreateProcessW` treats the second argument as a command line and splits it in two.  One solution to this would be to quote the argument, however I believe a  better solution would be to use `go env GOTOOLDIR` rather than listing `$(go env GOROOT)/pkg/tool`.  I can prepare a PR to make this change easily enough.

**Comment by adam-azarchs** [comment]
Actually, never mind, I don't think it's due to the space.  Even if I install `go` somewhere without a space (and have my `PATH` set to include `msys2` so it _should_ be able to find `ls`), I still get
```
 Could not detect SDK platform: unable to list C:\ProgramData\Golang/pkg/tool: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("ls" C:\ProgramData\Golang/pkg/tool): The system cannot find the file specified.
 ```
So now I'm suspecting the `\` characters might be to blame, but I really don't know.
